### ISSUE TITLE
Add bucket failed

### ISSUE THREAD

**Issue by ASHwaysama** [scoopcn/scoopcn#1]
Checking repo... 'git@github.com:scoopcn/scoopcn.git' doesn't look like a valid git repository

Error given:
Host key verification failed. fatal: Could not read from remote repository. System.Management.Automation.RemoteException Please make sure you have the correct access rights and the repository exists.

Solve：
Use
scoop bucket add scoopcn https://github.com/scoopcn/scoopcn.git

**Comment by sinloss** [comment]
Correct me if I'm wrong, to clone any repo via `ssh` you need to configure the *public/private key pairs* for GitHub so that you could access repositories.

Please make sure you have access to any GitHub repo via `ssh`.

It seems this issue is ready to close since you've already got a solution. Feel free to reopen this issue if you have any further considerations.
